import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const promptFont = localFont({
  src: [
    { path: "../public/fonts/prompt/Prompt-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/prompt/Prompt-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/prompt/Prompt-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../public/fonts/prompt/Prompt-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-sarabun",
  display: "swap",
  fallback: ["Leelawadee UI", "Tahoma", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/ThemeProvider";
import { LanguageProvider } from "@/lib/i18n/LanguageContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${promptFont.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
