// Labels shared with the standard document forms. Add labels here when introducing new form fields.
export const documentFieldLabels: Record<string, string> = {
  "employeeCode": "รหัสพนักงาน",
  "employeeName": "ชื่อพนักงาน",
  "position": "ตำแหน่ง",
  "department": "แผนก",
  "paymentDate": "วันที่จ่ายเงิน",
  "bankName": "ธนาคาร",
  "accountNo": "เลขที่บัญชี",
  "basicSalary": "เงินเดือนพื้นฐาน",
  "overtime": "ค่าล่วงเวลา (OT)",
  "allowances": "เบี้ยเลี้ยง / อื่นๆ",
  "bonus": "โบนัส",
  "taxDeduction": "ภาษีหัก ณ ที่จ่าย",
  "socialSecurity": "ประกันสังคม",
  "providentFund": "กองทุนสำรองเลี้ยงชีพ",
  "otherDeductions": "หักอื่นๆ",
  "remarks": "หมายเหตุเอกสาร (Document Remarks)",
  "registrationNumber": "ทะเบียนเลขที่",
  "meetingNo": "ครั้งที่ (Meeting No.)",
  "meetingDate": "เมื่อวันที่ (Meeting Date)",
  "registeredCapital": "ทุนจดทะเบียน (บาท)",
  "dividedInto": "แบ่งออกเป็น (หุ้น)",
  "valuePerShare": "มูลค่าหุ้นละ (บาท)",
  "thaiShareholdersCount": "จำนวน (คน)",
  "thaiShareholdersShares": "จำนวน (หุ้น)",
  "foreignShareholdersCount": "จำนวน (คน)",
  "foreignShareholdersShares": "จำนวน (หุ้น)",
  "pk0401_registrationNumber": "เลขทะเบียนนิติบุคคล",
  "pk0401_companyName": "ชื่อบริษัท / ห้างหุ้นส่วน",
  "pk0401_registrationDate": "วันที่จดทะเบียนนิติบุคคล",
  "pk0401_issueDate": "ออกให้ ณ วันที่ (Issue Date)",
  "pk0401_registrarName": "นายทะเบียน (Registrar)",
  "boj2_companyName": "ชื่อบริษัท (ตามที่ขอจดทะเบียน)",
  "boj2_province": "สำนักงานตั้งอยู่ ณ (จังหวัด)",
  "boj2_objectivesCount": "วัตถุประสงค์มี (ข้อ)",
  "boj2_capital": "ทุนจดทะเบียน (บาท)",
  "boj2_dividedInto": "แบ่งออกเป็น (หุ้น)",
  "boj2_valuePerShare": "มูลค่าหุ้นละ (บาท)",
  "msm_companyName": "ชื่อบริษัท",
  "msm_meetingDate": "วันและเวลาที่ประชุม",
  "msm_meetingLocation": "สถานที่ประชุม",
  "msm_chairman": "ประธานในที่ประชุม",
  "msm_totalShareholders": "ผู้ถือหุ้นเข้าประชุม (คน)",
  "msm_totalShares": "นับรวมกันได้ (หุ้น)",
  "msm_agenda": "วาระการประชุม และ มติที่ประชุม",
  "idCopy_directorName": "ชื่อ-นามสกุล กรรมการ",
  "idCopy_idCard": "เลขประจำตัวประชาชน",
  "idCopy_address": "ที่อยู่ตามทะเบียนบ้าน",
  "tax_year": "ปีภาษี (พ.ศ.)",
  "tax_companyName": "ชื่อผู้มีหน้าที่หักภาษี ณ ที่จ่าย",
  "tax_taxId": "เลขประจำตัวผู้เสียภาษีอากร",
  "tax_branch": "สาขาที่",
  "tax_totalIncome": "รวมยอดเงินได้พึงประเมินที่จ่าย",
  "tax_totalTax": "รวมยอดภาษีที่นำส่ง",
  "tax_surcharge": "เงินเพิ่ม (ถ้ามี)",
  "vat_year": "ปีภาษี (พ.ศ.)",
  "vat_salesAmount": "1. ยอดขายในเดือนนี้",
  "vat_zeroRateSales": "2. หัก ยอดขายที่เสียภาษี 0%",
  "vat_exemptSales": "3. หัก ยอดขายที่ได้รับยกเว้น",
  "vat_purchaseAmount": "6. ยอดซื้อที่มีสิทธินำมาหักภาษี",
  "invoice_number": "เลขที่ใบกำกับภาษี (Invoice No.)",
  "invoice_date": "วันที่ออกเอกสาร (Date)",
  "invoice_buyerName": "ชื่อผู้ซื้อ (Name)",
  "invoice_buyerTaxId": "เลขประจำตัวผู้เสียภาษี (Tax ID)",
  "invoice_buyerBranch": "สาขาที่ (Branch)",
  "invoice_buyerAddress": "ที่อยู่ (Address)",
  "tawi_documentNo": "เล่มที่ / เลขที่",
  "tawi_issueDate": "วัน/เดือน/ปี ที่ออกหนังสือ",
  "tawi_withholderName": "ชื่อ (ผู้จ่ายเงิน)",
  "tawi_withholderTaxId": "เลขประจำตัวผู้เสียภาษีอากร",
  "tawi_withholderAddress": "ที่อยู่",
  "tawi_payeeName": "ชื่อ (ผู้รับเงิน)",
  "tawi_payeeTaxId": "เลขประจำตัวผู้เสียภาษีอากร",
  "tawi_payeeAddress": "ที่อยู่",
  "tawi_incomeType": "ประเภทเงินได้พึงประเมิน",
  "tawi_incomeAmount": "จำนวนเงินที่จ่าย",
  "tawi_taxAmount": "ภาษีที่หักและนำส่งไว้",
  "pp20_taxId": "เลขประจำตัวผู้เสียภาษีอากร",
  "pp20_companyName": "ชื่อผู้ประกอบการ",
  "pp20_branchName": "ชื่อสถานประกอบการ",
  "pp20_address": "ที่ตั้งสถานประกอบการ",
  "pp20_issueDate": "ให้ไว้ ณ วันที่",
  "pnd50_periodStart": "สำหรับรอบระยะเวลาบัญชี เริ่มตั้งแต่",
  "pnd50_periodEnd": "ถึงวันที่",
  "pnd50_companyName": "ชื่อบริษัทหรือห้างหุ้นส่วนนิติบุคคล",
  "pnd50_taxId": "เลขประจำตัวผู้เสียภาษีอากร",
  "pnd50_netProfit": "กำไรสุทธิ / ประมาณการกำไรสุทธิ",
  "pnd50_taxAmount": "ภาษีที่คำนวณได้",
  "timesheet_month": "ประจำเดือน / ปี",
  "timesheet_employeeId": "รหัสพนักงาน (Emp ID)",
  "timesheet_employeeName": "ชื่อ-นามสกุลพนักงาน",
  "timesheet_position": "ตำแหน่ง (Position)",
  "timesheet_department": "แผนก (Department)",
  "leave_requestDate": "วันที่กรอกแบบฟอร์ม (Date)",
  "leave_employeeName": "ชื่อ-นามสกุลพนักงาน (Name)",
  "leave_employeeId": "รหัสพนักงาน (Emp ID)",
  "leave_position": "ตำแหน่ง (Position)",
  "leave_department": "แผนก (Department)",
  "leave_typeOther": "ระบุประเภทการลา (Specify)",
  "leave_reason": "เนื่องจาก (Reason)",
  "leave_startDate": "ตั้งแต่วันที่ (Start Date)",
  "leave_endDate": "ถึงวันที่ (End Date)",
  "leave_totalDays": "รวมเป็นเวลา (Total Days)",
  "sso_employerName": "ชื่อสถานประกอบการ (Employer Name)",
  "sso_employerAccount": "เลขที่บัญชีนายจ้าง (Employer Account No.)",
  "sso_branchNo": "ลำดับที่สาขา (Branch No.)",
  "sso_year": "พ.ศ. (Year)",
  "work_rules_companyName": "ชื่อสถานประกอบการ (Company Name)",
  "work_rules_effectiveDate": "วันที่มีผลบังคับใช้ (Effective Date)",
  "work_rules_probationPeriod": "ระยะเวลาทดลองงาน (Probation Period)",
  "work_rules_workingDays": "วันทำงานปกติ (Working Days)",
  "work_rules_workingHours": "เวลาทำงานปกติ (Working Hours)",
  "work_rules_breakTime": "เวลาพัก (Break Time)",
  "work_rules_publicHolidays": "วันหยุดประเพณี (Public Holidays)",
  "work_rules_annualLeave": "วันหยุดพักผ่อนประจำปี (Annual Leave)",
  "work_rules_sickLeave": "วันลาป่วย (Sick Leave)",
  "work_rules_personalLeave": "วันลากิจ (Personal Leave)",
  "work_rules_salaryPaymentDate": "กำหนดการจ่ายค่าจ้าง (Payment Schedule)",
  "contract_employerName": "ชื่อบริษัท / นายจ้าง (Employer Name)",
  "contract_employerAddress": "ที่ตั้งสำนักงาน (Office Address)",
  "contract_employeeName": "ชื่อ-นามสกุล (Employee Name)",
  "contract_employeeIdCard": "เลขประจำตัวประชาชน (ID Card)",
  "contract_employeeAddress": "ที่อยู่ตามทะเบียนบ้าน (Registered Address)",
  "contract_position": "ตำแหน่ง (Position)",
  "contract_department": "แผนก (Department)",
  "contract_startDate": "วันเริ่มงาน (Start Date)",
  "contract_salary": "อัตราค่าจ้าง (Salary) / เดือน",
  "contract_probation": "ระยะเวลาทดลองงาน (Probation)",
  "empProfile_firstName": "ชื่อ (First Name)",
  "empProfile_lastName": "นามสกุล (Last Name)",
  "empProfile_idCard": "เลขประจำตัวประชาชน (ID Card)",
  "empProfile_birthDate": "วันเกิด (Date of Birth)",
  "empProfile_nationality": "สัญชาติ (Nationality)",
  "empProfile_religion": "ศาสนา (Religion)",
  "empProfile_address": "ที่อยู่ปัจจุบัน (Current Address)",
  "empProfile_phone": "เบอร์โทรศัพท์ (Phone)",
  "empProfile_email": "อีเมล (Email)",
  "empProfile_emergencyContact": "ชื่อ-สกุล (Name)",
  "empProfile_emergencyPhone": "ความสัมพันธ์ (Relationship) & เบอร์โทร",
  "bp_projectName": "ชื่อโครงการ / แผนธุรกิจ (Project Name)",
  "bp_objective": "วัตถุประสงค์ (Objective)",
  "bp_targetAudience": "กลุ่มเป้าหมาย (Target Audience)",
  "bp_author": "ผู้รับผิดชอบ (Project Owner)",
  "bp_timeline": "ระยะเวลาดำเนินการ (Timeline)",
  "bp_budget": "งบประมาณ (Estimated Budget)",
  "bp_strategy": "กลยุทธ์การดำเนินงาน (Strategy)",
  "bp_expectedOutcome": "ผลลัพธ์ที่คาดหวัง (Expected Outcome)",
  "sop_title": "ชื่อคู่มือ / ขั้นตอน (SOP Title)",
  "sop_department": "แผนกที่รับผิดชอบ (Department)",
  "sop_effectiveDate": "วันที่บังคับใช้ (Effective Date)",
  "sop_revision": "ครั้งที่แก้ไข (Revision No.)",
  "sop_objective": "วัตถุประสงค์ (Objective/Purpose)",
  "sop_scope": "ขอบเขต (Scope)",
  "sop_definitions": "คำจำกัดความ (Definitions) - ถ้ามี",
  "sop_procedures": "ขั้นตอนการปฏิบัติงาน (Procedures)",
  "sop_references": "เอกสารอ้างอิง (References)",
  "vendorContract_partyA_name": "ชื่อบริษัท / นิติบุคคล (Company Name)",
  "vendorContract_partyA_address": "ที่อยู่ (Address)",
  "vendorContract_partyB_name": "ชื่อบริษัท / นิติบุคคล (Vendor Name)",
  "vendorContract_partyB_address": "ที่อยู่ (Address)",
  "vendorContract_serviceDescription": "รายละเอียดการให้บริการ (Service Description)",
  "vendorContract_contractDate": "วันที่ทำสัญญา (Contract Date)",
  "vendorContract_duration": "ระยะเวลาสัญญา (Duration)",
  "vendorContract_amount": "มูลค่าสัญญา / ค่าตอบแทน (Contract Amount)",
  "vendorContract_paymentTerms": "เงื่อนไขการชำระเงิน (Payment Terms)",
  "meeting_title": "หัวข้อการประชุม (Meeting Title)",
  "meeting_date": "วันที่ประชุม (Date)",
  "meeting_time": "เวลา (Time)",
  "meeting_location": "สถานที่ / ช่องทาง (Location / Platform)",
  "meeting_attendees": "รายชื่อผู้เข้าร่วมประชุม (Attendees)",
  "meeting_absentees": "รายชื่อผู้ไม่มาประชุม (Absentees) - ถ้ามี",
  "meeting_agenda": "วาระการประชุม และ ข้อหารือ (Agendas & Discussions)",
  "meeting_decisions": "มติที่ประชุม / ข้อตกลง (Decisions / Resolutions)",
  "meeting_actionItems": "สิ่งที่ต้องดำเนินการต่อ (Action Items)",
  "inventory_date": "วันที่ทำรายการ (Date)",
  "inventory_ref": "เอกสารอ้างอิง (Ref. Document)",
  "inventory_location": "สถานที่เก็บ / คลังสินค้า (Location / Warehouse)",
  "inventory_preparedBy": "ผู้รับผิดชอบ / ผู้บันทึก (Prepared By)",
  "inventory_itemsText": "รายละเอียดรายการสินค้า (Item Details)",
  "pr_requester": "ผู้ขอจัดซื้อ (Requester)",
  "pr_department": "แผนก (Department)",
  "pr_date": "วันที่ขอจัดซื้อ (PR Date)",
  "pr_neededBy": "วันที่ต้องการใช้งาน (Needed By)",
  "pr_purpose": "วัตถุประสงค์ในการจัดซื้อ (Purpose / Justification)",
  "pr_itemsText": "รายละเอียดรายการ (Item Details)",
  "pr_totalAmount": "ยอดรวมโดยประมาณ (Estimated Total)",
  "pr_suggestedVendor": "ผู้ขายที่แนะนำ (Suggested Vendor)",
  "lease_lessor_name": "ชื่อผู้ให้เช่า (Lessor Name)",
  "lease_lessor_address": "ที่อยู่ (Address)",
  "lease_lessee_name": "ชื่อผู้เช่า (Lessee Name)",
  "lease_lessee_address": "ที่อยู่ (Address)",
  "lease_property": "ทรัพย์สินที่เช่า / สถานที่เช่า (Leased Property / Premises)",
  "lease_purpose": "วัตถุประสงค์การเช่า (Purpose of Lease)",
  "lease_startDate": "วันที่เริ่มต้นสัญญา (Start Date)",
  "lease_endDate": "วันที่สิ้นสุดสัญญา (End Date)",
  "lease_rentalFee": "ค่าเช่าต่อเดือน (Monthly Rental Fee)",
  "lease_deposit": "เงินมัดจำ / เงินประกัน (Security Deposit)",
  "lease_paymentTerms": "กำหนดชำระเงิน (Payment Schedule)",
  "monthlyReport_month": "ประจำเดือน (Month / Year)",
  "monthlyReport_department": "แผนก (Department)",
  "monthlyReport_preparedBy": "ผู้จัดทำรายงาน (Prepared By)",
  "monthlyReport_summary": "สรุปผลการดำเนินงานภาพรวม (Executive Summary)",
  "monthlyReport_achievements": "ผลงานที่สำเร็จตามเป้าหมาย (Key Achievements)",
  "monthlyReport_issues": "ปัญหา และ อุปสรรค (Issues / Challenges)",
  "monthlyReport_nextPlan": "แผนงานในเดือนถัดไป (Next Month Plan)",
  "companyReg_name": "ชื่อบริษัท (Company Name)",
  "companyReg_date": "วันที่ประกาศใช้ (Effective Date)",
  "companyReg_chapter1": "หมวดที่ 1 บททั่วไป (Chapter 1: General Provisions)",
  "companyReg_chapter2": "หมวดที่ 2 หุ้นและผู้ถือหุ้น (Chapter 2: Shares and Shareholders)",
  "companyReg_chapter3": "หมวดที่ 3 คณะกรรมการบริษัท (Chapter 3: Board of Directors)",
  "companyReg_chapter4": "หมวดที่ 4 การประชุมผู้ถือหุ้น (Chapter 4: Shareholders&apos; Meetings)",
  "companyReg_chapter5": "หมวดที่ 5 อื่นๆ (Chapter 5: Miscellaneous) - ถ้ามี",
  "memo_header": "ส่วนราชการ / หน่วยงาน (Department / Header)",
  "memo_no": "ที่ (Ref No.)",
  "memo_date": "วันที่ (Date)",
  "memo_subject": "เรื่อง (Subject)",
  "memo_to": "เรียน (To)",
  "memo_content": "ข้อความ / รายละเอียด (Body / Content)",
  "memo_signature": "ลงชื่อ (Signature / Prepared By)",
  "memo_position": "ตำแหน่ง (Position)",
  "quotation_customerName": "ชื่อลูกค้า / บริษัท (Customer Name)",
  "quotation_customerAddress": "ที่อยู่ลูกค้า (Customer Address)",
  "quotation_date": "วันที่เสนอราคา (Date)",
  "quotation_validUntil": "ยืนราคาถึงวันที่ (Valid Until)",
  "quotation_refNo": "เลขที่อ้างอิง (Ref No. / Project Name)",
  "quotation_paymentTerms": "เงื่อนไขการชำระเงิน (Payment Terms)",
  "receipt_customerName": "ได้รับเงินจาก (Received From)",
  "receipt_customerAddress": "ที่อยู่ (Address)",
  "receipt_date": "วันที่รับเงิน (Date)",
  "receipt_refNo": "เลขที่ใบเสร็จ (Receipt No.)",
  "receipt_itemsText": "รายละเอียดการชำระเงิน (Payment For)",
  "receipt_totalAmount": "จำนวนเงินรวมทั้งสิ้น (Total Amount)",
  "receipt_bankRef": "ข้อมูลอ้างอิงการชำระเงิน (Payment Ref)",
  "taxReport_month": "ประจำเดือน / ปี (Month / Year)",
  "taxReport_companyName": "ชื่อผู้ประกอบการ (Company Name)",
  "taxReport_taxId": "เลขประจำตัวผู้เสียภาษี (Tax ID)",
  "taxReport_branch": "สาขาที่ (Branch)",
  "taxReport_itemsText": "รายละเอียดรายการ (Item Details)",
  "taxReport_totalAmount": "รวมมูลค่าสินค้า/บริการ (Total Amount)",
  "taxReport_totalTax": "รวมจำนวนเงินภาษีมูลค่าเพิ่ม (Total VAT)",
  "mou_title": "หัวข้อบันทึกข้อตกลง (MOU Title)",
  "mou_date": "วันที่ทำข้อตกลง (Date of Agreement)",
  "mou_partyA_name": "ฝ่ายที่ 1 (Party A)",
  "mou_partyB_name": "ฝ่ายที่ 2 (Party B)",
  "mou_objective": "วัตถุประสงค์ (Objectives / Purpose)",
  "mou_terms": "ข้อตกลงและเงื่อนไข (Terms & Conditions)",
  "mou_duration": "ระยะเวลาความร่วมมือ (Duration / Validity)",
  "po_vendorName": "ผู้จำหน่าย (Vendor Name)",
  "po_vendorAddress": "ที่อยู่ผู้จำหน่าย (Vendor Address)",
  "po_vendorTaxId": "เลขประจำตัวผู้เสียภาษี (Tax ID)",
  "po_refNo": "เลขที่ใบสั่งซื้อ (PO No.)",
  "po_date": "วันที่ (Date)",
  "po_dueDate": "ครบกำหนด (Due Date)",
  "po_buyer": "ผู้สั่งซื้อ (Buyer)",
  "po_projectName": "ชื่องาน (Project Name)",
  "po_contactName": "ผู้ติดต่อ (Contact Person)",
  "po_contactPhone": "เบอร์โทร (Phone)",
  "po_contactEmail": "อีเมล (Email)",
  "inv_customerName": "ชื่อลูกค้า (Customer Name)",
  "inv_customerAddress": "ที่อยู่ลูกค้า (Customer Address)",
  "inv_customerTaxId": "เลขประจำตัวผู้เสียภาษี (Tax ID)",
  "inv_refNo": "เลขที่ใบแจ้งหนี้ (Invoice No.)",
  "inv_date": "วันที่ (Date)",
  "inv_dueDate": "ครบกำหนด (Due Date)",
  "inv_seller": "ผู้ขาย (Seller)",
  "wht_payerName": "ชื่อผู้มีหน้าที่หักภาษี",
  "wht_payerAddress": "ที่อยู่",
  "wht_payerTaxId": "เลขประจำตัวผู้เสียภาษี (13 หลัก)",
  "wht_payeeName": "ชื่อผู้ถูกหักภาษี (บุคคล/นิติบุคคล)",
  "wht_payeeAddress": "ที่อยู่",
  "wht_payeeTaxId": "เลขประจำตัวผู้เสียภาษี (13 หลัก)",
  "wht_date": "วันที่ออกหนังสือรับรองฯ (Date)",
  "bizReg_companyName": "ชื่อที่ใช้ในการประกอบพาณิชยกิจ (Business Name)",
  "bizReg_registrationNo": "เลขทะเบียนพาณิชย์ (Registration No.)",
  "bizReg_registrationDate": "วันที่จดทะเบียน (Date of Registration)",
  "bizReg_ownerName": "ชื่อผู้ประกอบพาณิชยกิจ (Owner Name)",
  "bizReg_bizType": "ชนิดพาณิชยกิจ (Business Activities / Type)",
  "bizReg_address": "สำนักงานตั้งอยู่เลขที่ (Address)",
  "bizReg_registrar": "นายทะเบียน (Registrar - ถ้ามี)",
  "pv_payeeName": "จ่ายให้ (Payee Name)",
  "pv_payeeAddress": "ที่อยู่ (Address)",
  "pv_date": "วันที่ (Date)",
  "pv_refNo": "เลขที่ใบสำคัญ (Voucher No.)",
  "pv_bankRef": "ข้อมูลอ้างอิงการจ่าย (Bank / Cheque Ref)",
  "pv_taxAmount": "หักภาษี ณ ที่จ่าย (ถ้ามี)",
  "rv_payerName": "รับเงินจาก (Received From)",
  "rv_payerAddress": "ที่อยู่ (Address)",
  "rv_date": "วันที่ (Date)",
  "rv_refNo": "เลขที่ใบสำคัญ (Voucher No.)",
  "rv_bankRef": "ข้อมูลอ้างอิง (Bank / Cheque Ref)",
  "rv_itemsText": "รายละเอียดรายการรับเงิน (Receipt Description)",
  "rv_subTotal": "จำนวนเงิน (Amount)",
  "rv_taxAmount": "ถูกหักภาษี ณ ที่จ่าย (WHT - ถ้ามี)",
  "rv_grandTotal": "ยอดสุทธิ (Net Amount)",
  "gl_date": "วันที่บันทึก (Date)",
  "gl_refNo": "เลขที่เอกสารอ้างอิง (Ref. No. / Voucher No.)",
  "gl_entriesText": "รายละเอียดการบันทึกบัญชี (Entries Detail)",
  "gl_debit": "รวมเดบิต (Total Debit)",
  "gl_credit": "รวมเครดิต (Total Credit)",
  "stmt_accountName": "ชื่อบัญชี (Account Name)",
  "stmt_accountNo": "เลขที่บัญชี (Account No.)",
  "stmt_period": "รอบระยะเวลา Statement (Statement Period)",
  "stmt_beginningBalance": "ยอดยกมา (Beginning Balance)",
  "stmt_totalIn": "รวมยอดเงินเข้า (Total Deposit)",
  "stmt_totalOut": "รวมยอดเงินออก (Total Withdrawal)",
  "stmt_endingBalance": "ยอดยกไป (Ending Balance)",
  "stmt_entriesText": "บันทึกรายการบัญชีที่น่าสนใจ หรือต้องตรวจสอบ (Notes on specific entries)",
  "fa_assetCode": "รหัสทรัพย์สิน (Asset Code)",
  "fa_assetName": "ชื่อทรัพย์สิน (Asset Name)",
  "fa_acquisitionDate": "วันที่ได้มา (Acquisition Date)",
  "fa_cost": "ราคาทุน / มูลค่าที่ได้มา (Cost)",
  "fa_salvageValue": "ราคาซากโดยประมาณ (Salvage Value)",
  "fa_usefulLife": "อายุการใช้งาน (Useful Life)",
  "fa_location": "สถานที่ตั้ง / แผนกที่ใช้งาน (Location/Department)",
  "fs_companyName": "ชื่อกิจการ (Company Name)",
  "fs_periodEnd": "สำหรับรอบระยะเวลาสิ้นสุด (For the Period Ended)",
  "fs_totalAssets": "รวมสินทรัพย์ (Total Assets)",
  "fs_totalLiabilities": "รวมหนี้สิน (Total Liabilities)",
  "fs_totalEquity": "ส่วนของผู้ถือหุ้น (Total Equity)",
  "fs_totalRevenue": "รวมรายได้ (Total Revenue)",
  "fs_totalExpenses": "รวมค่าใช้จ่าย (Total Expenses)",
  "fs_netIncome": "กำไร(ขาดทุน)สุทธิ (Net Income/Loss)",
  "fs_auditorName": "ชื่อผู้สอบบัญชีรับอนุญาต (CPA Name)",
  "inv_invoiceNo": "เลขที่ใบแจ้งหนี้ (Invoice No.)",
  "inv_invoiceDate": "วันที่ (Date)",
  "discountPercent": "รูปแบบภาษี",
  "meetingType": "ประเภทการประชุม",
  "tax_formType": "ประเภทแบบยื่น",
  "tax_month": "เดือนที่จ่ายเงินได้",
  "vat_month": "เดือนภาษี",
  "vat_type": "ประเภทการยื่น",
  "invoice_type": "ประเภท",
  "pnd50_formType": "ประเภทแบบ",
  "sso_month": "ค่าจ้างเดือน (Wages for Month)",
  "empProfile_title": "คำนำหน้า (Title)",
  "empProfile_bloodType": "กรุ๊ปเลือด (Blood Type)",
  "inventory_type": "ประเภทรายการ (Transaction Type)",
  "receipt_paymentMethod": "วิธีการชำระเงิน (Payment Method)",
  "taxReport_type": "ประเภทรายงาน (Report Type)",
  "pv_paymentMethod": "ชำระโดย (Paid By)",
  "rv_paymentMethod": "รับชำระโดย (Received By)",
  "gl_bookType": "ประเภทสมุดบัญชี (Journal Type)",
  "stmt_bankName": "ชื่อธนาคาร (Bank Name)",
  "fa_assetType": "ประเภททรัพย์สิน (Asset Category)",
  "fa_depreciationMethod": "วิธีคิดค่าเสื่อมราคา (Depreciation Method)",
  "fa_status": "สถานะทรัพย์สิน (Asset Status)",
  "fs_statementType": "ประเภทงบการเงิน (Statement Type)",
  "fs_auditOpinion": "ความเห็นของผู้สอบบัญชี (Audit Opinion)",
  "priceType": "รูปแบบภาษี"
}
